[theme]

# Primary accent color for interactive elements.

primaryColor = "#d33682"

# Background color for the main content area.

backgroundColor = "#001B2E"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#2A0A12"

# Color used for almost all text
textColor = "#fff"